export type Direction = 'X' | 'Y'
export type Mode = 'placement' | 'game'
export type CellsDisplay = 'open' | 'close'
export type ShipState = 'onBoard' | 'attacked' | 'killed'
export type Turn = 'bot' | 'player'
export type CellAttack = 'killed' | 'damaged' | 'miss'
export type Order = '+' | '-'
